cp FILE001.WAV stabile-seitenlage-lang.wav
cp FILE002.WAV oeffnen-des-mundes-a.wav
cp FILE003.WAV oeffnen-des-mundes-b.wav
cp FILE004.WAV pruefen-der-atmung-kurz.wav
cp FILE005.WAV ueberstrecken-des-kopfes-a.wav
cp FILE006.WAV pruefen-der-atmung-lang.wav
cp FILE007.WAV pruefen-der-pupillenreaktion.wav
cp FILE008.WAV ueberstrecken-des-kopfes-b.wav
cp FILE009.WAV mund-zu-nase-beatmung-a.wav
cp FILE010.WAV mund-zu-nase-beatmung-b.wav
cp FILE011.WAV optimaler-druckpunkt-fuer-herz-druck-massage.wav
cp FILE012.WAV massnahmen-bei-bewusstlosigkeit.wav
cp FILE013.WAV falten-einer-dreieckstuchkrawatte.wav
cp FILE014.WAV kopfhaube-mit-dreieckstuch.wav
cp FILE015.WAV handverband-mit-dreieckstuch.wav
cp FILE016.WAV armverband-mit-dreieckstuch.wav
cp FILE017.WAV fussverband-mit-dreieckstuch.wav
cp FILE018.WAV fersenverband-mit-dreieckstuch.wav
cp FILE019.WAV unterschenkelverband-mit-dreieckstuch.wav
cp FILE020.WAV knieverband-mit-dreieckstuch.wav
cp FILE021.WAV augenverband-mit-dreieckstuch.wav
cp FILE022.WAV kinnverband-mit-dreieckstuch.wav
cp FILE023.WAV schulterverband-mit-dreieckstuch-a.wav
cp FILE024.WAV schulterverband-mit-dreieckstuch-b.wav
cp FILE025.WAV fingerverband-mit-verbandspaeckchen.wav
cp FILE026.WAV handverband-mit-verbandspaeckchen.wav
cp FILE027.WAV ellenbogenverband-mit-verbandspaeckchen.wav
cp FILE028.WAV knieverband-mit-verbandspaeckchen.wav
cp FILE029.WAV kopfverband-mit-verbandspaeckchen.wav
cp FILE030.WAV druckpolsterverband-mit-verbandspaeckchen.wav
cp FILE031.WAV druckpolsterverband-mit-dreieckstuch.wav
cp FILE032.WAV abdruecken-am-oberarm-mit-dreieckstuchkrawatte.wav
cp FILE033.WAV abdruecken-am-oberschenkel-mit-dreieckstuchkrawatte.wav
cp FILE034.WAV schultergelenkbruch-mit-dreieckstuch.wav
cp FILE035.WAV streifenverbaende-und-rahmenverbaende.wav
cp FILE036.WAV fingerkuppenverband-mit-pflaster.wav
cp FILE037.WAV abdruecken-einer-wunde.wav
cp FILE038.WAV normale-rueckenlage.wav
cp FILE039.WAV stabile-seitenlage-kurz.wav
cp FILE040.WAV rueckenlage-mit-knierolle.wav
cp FILE041.WAV schocklage.wav
cp FILE042.WAV rueckenlage-mit-erhoehtem-oberkoerper.wav
cp FILE043.WAV rettung-aus-dem-gefahrenbereich.wav
cp FILE044.WAV mundreinigung-vor-atemspende.wav
cp FILE045.WAV abnehmen-eines-motorradhelmes.wav
cp FILE046.WAV unfall-im-niederspannungsbereich.wav
cp FILE047.WAV ruhigstellung-eines-gebrochenen-beines.wav
cp FILE048.WAV abdruecken-der-oberarmschlagader.wav
cp FILE049.WAV abdruecken-der-oberschenkelschlagader.wav
cp FILE050.WAV puls-am-hals-ertasten.wav
cp FILE051.WAV zwoelffingerdarm.wav
cp FILE052.WAV akustisches-assoziationszentrum.wav
cp FILE053.WAV haut.wav
cp FILE054.WAV knochen.wav
cp FILE055.WAV auge.wav
cp FILE056.WAV knoecherne-augenhoehle.wav
cp FILE057.WAV bewegungsapparat-der-auges.wav
cp FILE058.WAV bandscheiben.wav
cp FILE059.WAV bauchwandmuskulatur.wav
cp FILE060.WAV becken.wav
cp FILE061.WAV befruchtung.wav
cp FILE062.WAV geschmacksorgan.wav
cp FILE063.WAV blinddarm.wav
cp FILE064.WAV blut-a.wav
cp FILE065.WAV b-lymphozyten.wav
cp FILE066.WAV nierenkoerperchen.wav
cp FILE067.WAV bronchien.wav
cp FILE068.WAV brustkorb.wav
cp FILE069.WAV brustwarze.wav
cp FILE070.WAV brust-der-frau.wav
cp FILE071.WAV verdauungssystem-a.wav
cp FILE072.WAV eierstock.wav
cp FILE073.WAV elle.wav
cp FILE074.WAV ellenbogengelenk.wav
cp FILE075.WAV speiche.wav
cp FILE076.WAV flexoren-des-unterarms.wav
cp FILE077.WAV fingerhandknochen.wav
cp FILE078.WAV follikel.wav
cp FILE079.WAV fussknochen.wav
cp FILE080.WAV gaumen.wav
cp FILE081.WAV gesaessmuskulatur.wav
cp FILE082.WAV glatte-muskulatur.wav
cp FILE083.WAV muskeln-und-sehnen.wav
cp FILE084.WAV haemoglobin.wav
cp FILE085.WAV handknochen.wav
cp FILE086.WAV harnblase.wav
cp FILE087.WAV handwurzelknochen.wav
cp FILE088.WAV herz.wav
cp FILE089.WAV gehirn-a.wav
cp FILE090.WAV endhirn.wav
cp FILE091.WAV hoden.wav
cp FILE092.WAV hodensack.wav
cp FILE093.WAV hoerzentrum.wav
cp FILE094.WAV hueftgelenk.wav
cp FILE095.WAV augapfel.wav
cp FILE096.WAV glied.wav
cp FILE097.WAV niere-a.wav
cp FILE098.WAV kehlkopf-a.wav
cp FILE099.WAV kiefergelenk.wav
cp FILE100.WAV knie-bandscheiben-und-menisken.wav
cp FILE101.WAV kniegelenk.wav
cp FILE102.WAV kniegelenk-baender.wav
cp FILE103.WAV kniescheibe.wav
cp FILE104.WAV knochengewebe.wav
cp FILE105.WAV nasenhoehlen-a.wav
cp FILE106.WAV nasennebenhoehlen.wav
cp FILE107.WAV kehlkopf-b.wav
cp FILE108.WAV kehlkopf-knorpelskelett.wav
cp FILE109.WAV kehlkopf-muskulatur.wav
cp FILE110.WAV luftroehre-a.wav
cp FILE111.WAV lungen-a.wav
cp FILE112.WAV lungenarterien-und-lungenvenen.wav
cp FILE113.WAV fortpflanzung-a.wav
cp FILE114.WAV geschlechtsorgane-der-frau-a.wav
cp FILE115.WAV schamlippen.wav
cp FILE116.WAV kitzler.wav
cp FILE117.WAV eileiter.wav
cp FILE118.WAV gebaermutter.wav
cp FILE119.WAV scheide.wav
cp FILE120.WAV atmungssystem.wav
cp FILE121.WAV nasenhoehlen-b.wav
cp FILE122.WAV kehlkopf-c.wav
cp FILE123.WAV luftroehre-b.wav
cp FILE124.WAV lungen-b.wav
cp FILE125.WAV fortpflanzung-b.wav
cp FILE126.WAV geschlechtsorgane-der-frau-b.wav
cp FILE127.WAV geschlechtsorgane-des-mannes.wav
cp FILE128.WAV harnsystem.wav
cp FILE129.WAV niere-b.wav
cp FILE130.WAV harnleiter.wav
cp FILE131.WAV nervensystem.wav
cp FILE132.WAV zentrales-nervensystem.wav
cp FILE133.WAV rueckenmark.wav
cp FILE134.WAV gehirn-b.wav
cp FILE135.WAV peripheres-nervensystem.wav
cp FILE136.WAV animalisches-nervensystem.wav
cp FILE137.WAV vegetatives-nervensystem.wav
cp FILE138.WAV nervengewebe.wav
cp FILE139.WAV sinnesorgane.wav
cp FILE140.WAV auge.wav
cp FILE141.WAV ohr.wav
cp FILE142.WAV nase-riechorgan.wav
cp FILE143.WAV verdauungssystem-b.wav
cp FILE144.WAV kauapparat.wav
cp FILE145.WAV schlund.wav
cp FILE146.WAV speiseroehre.wav
cp FILE147.WAV magen.wav
cp FILE148.WAV duenndarm.wav
cp FILE149.WAV leber.wav
cp FILE150.WAV bauspeicheldruese.wav
cp FILE151.WAV bewegungsapparat.wav
cp FILE152.WAV skelett.wav
cp FILE153.WAV knochengewebe.wav
cp FILE154.WAV skelettmuskulatur.wav
cp FILE155.WAV bewegungsapparat-obere-gliedmasse.wav
cp FILE156.WAV bewegungsapparat-untere-gliedmasse.wav
cp FILE157.WAV rumpf.wav
cp FILE158.WAV kopf.wav
cp FILE159.WAV kreislaufsystem.wav
cp FILE160.WAV herz.wav
cp FILE161.WAV blut-b.wav
cp FILE162.WAV endokrines-system.wav
cp FILE163.WAV hirnanhangdruese.wav
cp FILE164.WAV zirbeldruese.wav
cp FILE165.WAV schilddruese.wav
cp FILE166.WAV nebennieren.wav
cp FILE167.WAV haut.wav
cp FILE168.WAV haut-oberhaut.wav
cp FILE169.WAV haut-lederhaut.wav
cp FILE170.WAV haut-unterhaut.wav
cp FILE171.WAV lymphsystem.wav
cp FILE172.WAV lymphknoten.wav
cp FILE173.WAV milz.wav
cp FILE174.WAV mandeln.wav
cp FILE175.WAV thymus.wav
